kitchen/urls.py
from django.conf.urls import patterns, url

from kitchen import views

urlpatterns = patterns('kitchen.views',
    #url(r'transaction/$', views.TransactionList.as_view()),
    url(r'^$',                      views.home,  name="home"),
    url(r'tree/$',                  views.tree,  name="tree"),
    url(r'item/$',                  views.ItemList.as_view()),
    url(r'inventory/$',             views.inventory,         name='inventory'),
    url(r'shoppinglist/$',          views.shoppinglist_view, name='shoppinglist'),
    url(r'recipe_list/$',           views.recipe_list,       name='recipe_list'),
    url(r'recipe_add/$',            views.recipe_add,        name='recipe_add'),
    url(r'create_recipe/$',         views.create_recipe,       name='create_recipe'),
    url(r'recipeorder_list/$',      views.recipeorder_list,    name='recipeorder_list'),
    url(r'ingredient_add',          views.ingredient_add,      name='ingredient_add'),
    url(r'ingredient_create',       views.ingredient_create,   name='ingredient_create'),
    url(r'^(?P<ing_id>\d+)/ing_delete', views.ing_delete,           name='ing_delete'),
    url(r'item_selector/$',         views.item_selector,       name='item_selector'),
    url(r'item_selector_final/$',   views.item_selector_final, name='item_selector_final'),
    url(r'item_selector_test/$',    views.item_selector_test,  name='item_selector_test'),
    url(r'^(?P<recipe_id>\d+)/create_recipe_order/$',   views.create_recipe_order, name='create_recipe_order'),
    url(r'^(?P<recipe_id>\d+)/recipe_edit/$',           views.recipe_edit,         name='recipe_edit'),
    url(r'^(?P<recipeorder_id>\d+)/recipeorder_edit/$',     views.recipeorder_edit,    name='recipeorder_edit'),
    url(r'^(?P<recipeorder_id>\d+)/recipeorder_cancel/$',   views.recipeorder_cancel,   name='recipeorder_cancel'),
    url(r'^(?P<store_id>\d+)/store_edit/$',                 views.store_edit,          name='store_edit'),
    )

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'kitchen.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^kitchen/',  include('kitchen.urls',  namespace="kitchen")),
    url(r'^admin/', include(admin.site.urls)),
)

kitchen/models.py
from django.db import models

# Create your models here.

class MeasurementType(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField(max_length=256)
    measurementtype = models.ForeignKey(MeasurementType)
    
    convert = models.FloatField(null=True)
    
    def __unicode__(self):
        return self.name

#class CategoryBase(models.Model):
#    class Meta:
#        #abstract = True
#        pass

#class CategoryRelation(models.Model):
#    parent = models.ForeignKey(CategoryBase,related_name='+')
#    child  = models.ForeignKey(CategoryBase,related_name='+')

#class Category(CategoryBase):
class Category(models.Model):
    name   = models.CharField(max_length=256)
    #parent = models.ForeignKey(Category, null=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

class CategoryRelation(models.Model):
    parent = models.ForeignKey(Category,related_name='+')
    child  = models.ForeignKey(Category,related_name='+')

    def __unicode__(self):
        return self.parent.name + " --- " + self.child.name
   

class Item(models.Model):

    name = models.CharField(max_length=256)
    unit = models.ForeignKey(Unit, null=True)

    category = models.ForeignKey(Category, null=True)
    price  = models.FloatField(null=True)

    def __unicode__(self):
        #return "Item:" + self.name
        return self.name

    def get_category(self):
        
        c = self.category

        while True:
            lst_cr = CategoryRelation.objects.filter(child = c)
            
            if not lst_cr:
                return c
            else:
                c = lst_cr[0].parent

    class Meta:
        ordering = ('name',)

class Recipe(models.Model):
    name = models.CharField(max_length=256)
    source = models.CharField(max_length=256, blank=True)
    lcm = models.FloatField(default=1.0)
    ingredients = models.ManyToManyField(Item, through='Ingredient')
    text = models.TextField(blank=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return "Recipe:" + self.name
    def can_make(self, a, ir_dict):
        #print("can_make")
        #print(ir_dict)

        ings = Ingredient.objects.filter(recipe=self, amount__gt=0)
        
        #print(ings)

        for ing in ings:
            need = a * ing.amount_std

            if not ing.item in ir_dict:
                if need > 0:
                    return False

            ir = ir_dict[ing.item]
            
            if ir < need:
                return False

        return True

class RecipeOrder(models.Model):

    PLANNED  = '0'
    COMPLETE = '1'
    CANCELED = '2'
    STATUS_CHOICES = (
        (PLANNED,  'planned'),
        (COMPLETE, 'complete'),
        (CANCELED, 'canceled'),
        )
                        
    recipe = models.ForeignKey(Recipe)
    amount = models.FloatField()
    status = models.CharField(max_length=1,
        choices=STATUS_CHOICES,
        default=PLANNED)

    def __unicode__(self):
        return self.recipe.name + ": " + str(self.amount)

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe)
    item = models.ForeignKey(Item)
    unit = models.ForeignKey(Unit)
    amount = models.FloatField()
    optional = models.BooleanField(default=False)
    def __unicode__(self):
        return self.recipe.name + ": " + self.item.name
    def _get_amount_std(self):
        return self.amount * self.unit.convert
    amount_std = property(_get_amount_std)
    
class RecipeOrderTransaction(models.Model):
    recipeorder = models.ForeignKey(RecipeOrder)
    ingredient  = models.ForeignKey(Ingredient)
    unit        = models.ForeignKey(Unit)
    amount      = models.FloatField()

    def _get_amount_std(self):
        return self.amount * self.unit.convert

    amount_std = property(_get_amount_std)

class Transaction(models.Model):
    item   = models.ForeignKey(Item)
    unit   = models.ForeignKey(Unit)
    amount = models.FloatField()
    def __unicode__(self):
        return self.item.name + ":" + str(self.amount_std)
    def _get_amount_std(self):
        return self.amount * self.unit.convert
    amount_std = property(_get_amount_std)

class Store(models.Model):
    name = models.CharField(max_length=256)
    categories = models.ManyToManyField(Category, through='StoreCategory')
 
    def __unicode__(self):
        return self.name
   
class StoreCategory(models.Model):
    store    = models.ForeignKey(Store)
    category = models.ForeignKey(Category)
    order    = models.FloatField()

    class Meta:
        ordering = ('order',)
    

kitchen/forms.py
import django.forms

import kitchen.models

class add_recipe(django.forms.Form):
    name   = django.forms.CharField(max_length=256)
    source = django.forms.CharField(max_length=256)
    lcm    = django.forms.FloatField()
    #ingredients = models.ManyToManyField(Item, through='Ingredient')
    #text   = django.forms.TextField()

class ingredient_add(django.forms.Form):
    unit   = django.forms.ModelChoiceField(queryset=kitchen.models.Unit.objects.all())
    amount = django.forms.DecimalField()

kitchen/views.py
import math
import itertools

from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.shortcuts import get_object_or_404, HttpResponseRedirect, HttpResponse
import django.db.models
import django.views.generic

from kitchen.models import *

import kitchen.graph
import kitchen.forms
import kitchen.funcs
import kitchen.classes

def shoppinglist(store_id = None):

    G = kitchen.graph.IngGraph()
    
    dlist = list(kitchen.funcs.demand_list())
    
    ir_dict = dict((item, ir) for item, ir in kitchen.funcs.ir_list())
    
    for item, ir, d in dlist:
        
        # d = amount in item.unit units

        amount = d / item.unit.convert

        if item.price:
            price = amount * item.price
        else:
            price = 0

        #in_e = G.G.in_edges(item, data=True)

        recipes = list(kitchen.funcs.test_in(G, item, d, ir_dict))
        
        cat = kitchen.funcs.category_top_for(item.category)
        
        try:
            store = kitchen.models.Store.objects.get(pk=store_id)
            storecat = kitchen.models.StoreCategory.objects.filter(store=store, category=cat)
            try:
                order = storecat[0].order
            except:
                order = 100000000
        except:
            order = 100000000
        
        #yield item, d / item.unit.convert, item.unit, cat, recipes, order
        yield kitchen.classes.shoppinglist_data(
                item,
                d / item.unit.convert,
                item.unit,
                cat,
                recipes,
                order,
                price)

class ItemList(django.views.generic.ListView):
    
    def get_queryset(self):
        return Item.objects.all()

def inventory(request):

    context = {'items': list(kitchen.funcs.inventory())}
    
    return render(request, 'kitchen/inventory.html', context)

def sum(lst, f):
    ret = 0
    for l in lst:
        ret += f(l)
    return ret

def shoppinglist_view(request):

    try:
        store_id = request.POST['store_id']
    except:
        store_id = None

    items = sorted(list(shoppinglist(store_id)), key = lambda x: x.order)
    
    a = -1
    c = None
    for i in items:
        if i.cat != c:
            a = (a+1) % 6
            c = i.cat

        i.color = "color{}".format(a)

    context = {
            'items':  items,
            'stores': kitchen.models.Store.objects.all(),
            'store_id': store_id,
            'price_sum': sum(items, lambda i: i.price),
            }
    
    return render(request, 'kitchen/shoppinglist.html', context)

def recipeorder_list(request):
    recipeorders = kitchen.models.RecipeOrder.objects.filter(status=kitchen.models.RecipeOrder.PLANNED)
    return render(request, 'kitchen/recipeorder_list.html', {'recipeorders':recipeorders})

def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'kitchen/recipe_list.html', {'recipes':recipes})

def recipe_edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=int(recipe_id))
    return render(request, 'kitchen/recipe_edit.html', {
        'recipe':      recipe,
        'ingredients': Ingredient.objects.filter(recipe=recipe),
        })

# create a new recipe
def create_recipe(request):

    try:
        name = request.POST['name']
    except KeyError:
        return render(request, 'kitchen/error.html', {'message':'create recipe: KeyError'})
    else:
        r = Recipe()
        r.name = name
        r.save()
        
        #return render(request, 'kitchen/error.html', {'message':'create recipe: Success'})
        return recipe_edit(request, r.id)
        #return HttpResponse('/django/admin/')
        #return HttpResponseRedirect("/ite2/kitchen/{}/recipe_edit/".format(r.id))

def ingredient_create(request):
    
    try:
        recipe_id = request.POST['recipe_id']
        item_id   = request.POST['item_id']
        unit_id   = request.POST['unit']
        amount    = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/error.html', {'message':'create recipe: KeyError'})
    else:
        recipe = get_object_or_404(Recipe, pk=int(recipe_id))
        item   = get_object_or_404(Item,   pk=int(item_id))
        unit   = get_object_or_404(Unit,   pk=int(unit_id))
        
        i = Ingredient()
        
        i.recipe = recipe
        i.item = item
        i.unit = unit
        i.amount = amount

        i.save()

        return HttpResponseRedirect("/site_kitchen/kitchen/{}/recipe_edit/".format(recipe_id))
def ing_delete(request, ing_id):
    ing = get_object_or_404(Ingredient, pk=ing_id)
    ing.delete()
    return HttpResponseRedirect("/site_kitchen/kitchen/{}/recipe_edit/".format(ing.recipe.id))

def create_recipe_order(request, recipe_id):
    
    r = get_object_or_404(Recipe, pk=recipe_id)

    try:
        amount = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/shoppinglist.html', {'items':[]})
    else:
        ro = RecipeOrder()
        ro.recipe = r
        ro.amount = amount
        ro.save()

        return HttpResponseRedirect(reverse('kitchen:shoppinglist_view'))
    
def create_transaction(request, item_id):
    
    item = get_object_or_404(Item, pk=item_id)
    
    try:
        amount = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/shoppinglist.html', {'items':[]})
    else:
        t = Transaction()
        t.item = item
        t.amount = amount
	t.unit = item.unit
        t.save()

        return HttpResponseRedirect(reverse('kitchen:shoppinglist_view'))

def recipe_add(request):
    if request.method == 'POST':
        form = kitchen.forms.add_recipe(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/admin/')
    else:
        form = kitchen.forms.add_recipe()

    return render(request, 'kitchen/add_recipe.html', {'form':form})

def home(request):
    return render(request, 'kitchen/home.html', {})

def item_selector_final(request):
 
    # pass through
    pass_through = []
    for p in request.POST.items():
        if p[0][0:3] == 'ud_':
            pass_through.append(p)
   
    cat_name = request.POST['cat']

    action = request.POST['ud_action']

    cat = kitchen.models.Category.objects.get(name=cat_name)

    items = Item.objects.filter(category=cat)

    context = {
            'choices': items,
            'action': action, #'kitchen:item_selector_test',
            'pass_through': pass_through,
    }
    
    temp = 'kitchen/item_selector_final_1.html'

    return render(request, temp, context)

def item_selector(request):

    # pass through
    pass_through = []
    for p in request.POST.items():
        if p[0][0:3] == 'ud_':
            pass_through.append(p)

    try:
        cat = request.POST['cat']
    except KeyError:
        cat = None
        #return render(request, 'kitchen/error.html', {'message':'item selector: KeyError'})
    
    #tree = kitchen.funcs.item_selector_tree(selections)

    tree = kitchen.funcs.item_selector_tree2(cat)
    
    context = {
            'cat': cat,
            'pass_through': pass_through,#request.POST.items(),
            'extra': pass_through,#request.POST.items(),
            }
    
    #if isinstance(tree, list):
    if not tree:

        return item_selector_final(request)


        if not cat:
            return render(request, 'kitchen/error.html', {'message':'item selector: no category'})

        choices = kitchen.funcs.category_get_items(cat)
        context['action'] = 'kitchen:item_selector_test'
        temp = 'kitchen/item_selector_final_0.html'
    else:
        choices = tree
        temp = 'kitchen/item_selector.html'

    context['choices'] = choices

    return render(request, temp, context)

  

def item_selector_test(request):
    name = request.POST['name']
    return HttpResponse("you selected item: {}".format(name))

def item_list(request):
    items = kitchen.funcs.item_list()
    context = {'items':items}
    return render(request, 'kitchen/item_list.html', context)

def ingredient_add(request):

    recipe_id = request.POST['ud_recipe_id']

    item_id = request.POST['item_id']

    form = kitchen.forms.ingredient_add(request.POST)

    context = {
            'form':      form,
            'recipe_id': recipe_id,
            'item_id':   item_id,
            }

    return render(request, 'kitchen/ingredient_add.html', context)

def parse_ing_id(s):
    if s[0:4] == "ing_":
        if s[5] == "_":
            return int(s[4])
        elif s[6] == "_":
            return int(s[4:5])
        else:
            return None
    else:
        return None

def recipeorder_edit(request, recipeorder_id):
    recipeorder = get_object_or_404(RecipeOrder, pk=recipeorder_id)

    try:
        request.POST['btnComplete']

        # insert code for when recipe order is completed
        # the extra unit and quantity are for creating inventory transation for what was actually used
    except:
        pass
    else:
        # dont really know what this was...
        ings = {}
        for k,v in request.POST.items():
            pass
            #if 
            #    ings[int(k[])]


    context = {
            'recipeorder': recipeorder,
            'ingredients': kitchen.models.Ingredient.objects.filter(recipe=recipeorder.recipe),
            'units':       kitchen.models.Unit.objects.all(),
            #'ings':        ings,
            }
    return render(request, "kitchen/recipeorder_edit.html", context)

def recipeorder_cancel(request, recipeorder_id):
    recipeorder = get_object_or_404(RecipeOrder, pk=recipeorder_id)

    recipeorder.status = kitchen.models.RecipeOrder.CANCELED

    recipeorder.save()

    return recipeorder_list(request)

def tree(request):
    
    c_lst = Category.objects.all()

    cr_lst = CategoryRelation.objects.all()

    c_lst_0 = []

    for c in c_lst:
        if not kitchen.funcs.category_is_child(c):

kitchen/templates/kitchen/add_recipe.html
<table>
<form action="/django/kitchen/create_recipe/" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit" />
</form>
</table>

kitchen/templates/kitchen/base.html
{% load staticfiles %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static "kitchen/style.css" %}"/>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<style>
			div.left {
				float: left;
				width: 200px;
			}
			div.center {
				margin-left: 200px;
			}
			form {
				margin: 0px;
			}
			{% block style %}
			{% endblock %}
		</style>
		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div class="left">
			<a href="{% url 'admin:index'  %}">admin</a><br>
			<a href="{% url 'kitchen:home' %}">home</a><br>
			<h3>Tools</h3>
			<a href="{% url 'kitchen:shoppinglist' %}">shoppinglist</a><br>
			<h3>Recipes</h3>
			<a href="{% url 'kitchen:recipe_add'  %}">add</a><br>
			<a href="{% url 'kitchen:recipe_list' %}">list</a><br>
			<h3>Recipe Orders</h3>
			<a href="{% url 'kitchen:recipeorder_list' %}">list</a><br>

		</div>
		<div class="center">
			{% block content %}
			{% endblock %}
		</div>
	{% block foot %}
	{% endblock %}
	</body>
</html>

kitchen/templates/kitchen/error.html
{{ message }}

kitchen/templates/kitchen/home.html
{% extends 'kitchen/base.html' %}

{% block content %}
<h1>Kitchen Database</h1>
{% endblock %}

kitchen/templates/kitchen/inventory.html
<table>
{% for item, a, gpr in items %}
<tr>
	<td>{{ item }}</td>
	<td>{{ a }}</td>
	<td>
	<table>
		{% for g in gpr %}
			<tr><td>{{ g }}</td></tr>
		{% endfor %}
	</table>
	</td>
</tr>
{% endfor %}
</table>

kitchen/templates/kitchen/item_selector.html
<html>
	{% for c in choices %}
	<form action="{% url 'kitchen:item_selector' %}" method="post">
		{% csrf_token %}
		<!-- pass_through -->
		{% for p0,p1 in pass_through %}
			<input type="hidden" name="{{ p0 }}" value="{{ p1 }}"/>
		{% endfor %}
		<!---->
		<input type="hidden" name="cat" value="{{ c }}"/>
		<input type="submit" value="{{ c }}">
	</form>
	{% endfor %}

	{% for e in extra %}
	{{ e }}<br>
	{% endfor %}

	{{ choices }}
</html>

kitchen/templates/kitchen/item_selector_final_0.html
<html>
	{% for c in choices %}
	<form action="{% url 'kitchen:item_selector_final' %}" method="post">
		{% csrf_token %}
		<!-- pass_through -->
		{% for p0,p1 in pass_through %}
			<input type="hidden" name="{{ p0 }}" value="{{ p1 }}"/>
		{% endfor %}
		<!---->
		<input type="hidden" name="name" value="{{ c }}"/>
		<input type="submit" value="{{ c }}">
	</form>
	{% endfor %}
</html>

kitchen/templates/kitchen/item_selector_final_1.html
<html>
	{% for c in choices %}
	<form action="{% url action %}" method="post">
		{% csrf_token %}
		<!-- pass_through -->
		{% for p0,p1 in pass_through %}
			<input type="hidden" name="{{ p0 }}" value="{{ p1 }}"/>
		{% endfor %}
		<!---->
		<input type="hidden" name="name" value="{{ c }}"/>
		<input type="hidden" name="item_id" value="{{ c.id }}"/>
		<input type="submit" value="{{ c }}">
	</form>
	{% endfor %}
</html>

kitchen/templates/kitchen/recipe_list.html
<html>
{% extends "kitchen/base.html" %}

{% block style %}
form {
	margin:0px;
}
{% endblock %}

{% block content %}
<table>
{% for r in recipes %}
<tr>
	<td>{{ r.name }}</td>
	<td>
		<form action="{% url 'kitchen:recipe_edit' r.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="edit">
		</form>
	</td>
</tr>
{% endfor %}
</table>
{% endblock %}

kitchen/templates/kitchen/recipeorder_edit.html
<html>
	<head>
		<style>
			table, td {
				border: 1px solid black;
				border-collapse: collapse;
			}
			td {
				padding: 3px;
			}
		</style>
	</head>
	<body>
		{{ recipeorder.status }}
		<form action="{% url 'kitchen:recipeorder_edit' recipeorder.id %}" method="post" id="form">
		{% csrf_token %}
		<table>
			{% for ing in ingredients %}
			<tr>
				<td>{{ ing.item.name }}</td>
				<td>{{ ing.unit.name }}</td>
				<td>{{ ing.amount }}</td>
				<td>
					<select name="ing_{{ ing.id }}_unit_id" form="form">
						{% for unit in units %}
						<option value="{{ unit.id }}" {% if unit == ing.unit %}selected{% endif %}>{{ unit.name }}</option>
						{% endfor %}
					</select>
				</td>
				<td><input type="number" name="ing_{{ ing.id }}_amount" value="{{ ing.amount }}"></td>
			</tr>
			{% endfor %}
		</table>
		<input type="submit" name="btnComplete" value="complete">
		</form>

		{{ ings }}
	</body>
</html>

kitchen/templates/kitchen/recipeorder_list.html
{% extends "kitchen/base.html" %}

{% block content %}
<table>
{% for ro in recipeorders %}
<tr>
	<td>{{ ro.recipe.name }}</td>
	<td>
		<form action="{% url 'kitchen:recipeorder_edit' ro.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="edit">
		</form>
	</td>
	<td>
		<form action="{% url 'kitchen:recipeorder_cancel' ro.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="cancel">
		</form>
	</td>
</tr>
{% endfor %}
</table>
{% endblock %}

kitchen/templates/kitchen/store_edit.html
{% extends 'kitchen/base.html' %}

{% load staticfiles %}

{% block head %}
<script src="{% static 'kitchen/Sortable/Sortable.js' %}"></script>
{% endblock %}

{% block content %}

<ul id="sort_list">
	{% for c in categories %}
	<li class="drag_handle">
		{{ c.category.name }} {{ c.order }}
		<input id="order" type="hidden" name="{{ c.id }}_order" value="{{ c.order }}"></input>
	</li>
	{% endfor %}
</ul>

{% endblock %}

{% block foot %}
<script>
	var container = document.getElementById("sort_list");
	var sort = Sortable.create(container, {
		animation: 150, // ms, animation speed moving items when sorting, `0` — without animation
		handle: ".drag_handle", // Restricts sort start click/touch to the specified element
		onUpdate: function (evt/**Event*/){
			var item = evt.item; // the current dragged HTMLElement
			var i = item.querySelector("#order");

			var c = item.closest("li");

			var p = $(c).prev();
			var n = $(c).next();

			var p_str = "none";
			var n_str = "none";

			var p_order = 0;
			//if (!jQuery.isEmptyObject(p)) {
			if (p[0] != undefined) {
				p_str = p[0].innerHTML;
				p_order = parseFloat(p[0].querySelector("#order").value);
				//p_str = "not none";
				//p_str = jQuery.type(p);
				//p_str = p[0];
			} else {
				alert("top of list");
			}

			var n_order = 0;
			if (n[0] != undefined) {
				n_str = n[0].innerHTML;
				n_order = parseFloat(n[0].querySelector("#order").value);
			} else {
				alert("bottom of list");
			}

			var order = 100;
			if ((p[0] == undefined) && (n[0] == undefined)) {
				order = 100;
			} else if(p[0] == undefined) {
				order = n_order - 10;
			} else if(n[0] == undefined) {
				order = p_order + 10;
			} else {
				order = (p_order + n_order) / 2;
			}
			
			i.value = order;

			alert("new order = " + order);
			//alert(p_str + c.innerHTML + n_str);
			//alert(p[0].innerHTML + c.innerHTML + n[0].innerHTML);
		}
	});
</script>
{% endblock %}

kitchen/templates/kitchen/transaction_list.html
{#{% extends "base.html" %}#}

{% block content %}
<h2>Publishers</h2>
<ul>
{% for transaction in object_list %}
<li>{{ transaction.item.name }}</li>
{% endfor %}
</ul>
{% endblock %}

kitchen/templates/kitchen/tree.html
<head>
	<style>
		table, td {
			border: solid 1px;
		}
		.cat {
			background-color:#DDDDFF;
		}
		.item {
			background-color:#DDFFDD;
		}
	</style>
</head>

<table>
	{% for c0,l0,il0 in c_lst_0 %}
	<tr>
		<td>{{ c0.name }}</td>
		<td><table>
			{% for c1,l1,il1 in l0 %}
			<tr>
				<td class="cat">{{ c1.name }}</td>
				<td><table>
					{% for c2,l2,il2 in l1 %}
					<tr>
						<td class="cat">{{ c2.name }}</td>
						<td><table>
							{% for c3,l3,il3 in l2 %}
							<tr>
								<td class="cat">{{ c3.name }}</td>
								<td><table>
									{% for c4,l4,il4 in l3 %}
									<tr>
										<td class="cat">{{ c4.name }}</td>
										<td><table>
											{% for c5,l5,il5 in l4 %}
											<tr>
												<td class="cat">{{ c5.name }}</td>
												<td><table>
													{% for c6,l6,il6 in l5 %}
													<tr>
														<td class="cat">{{ c6.name }}</td>
														<td><table>
															{% for c7,l7,il7 in l6 %}
															<tr>
																<td class="cat">{{ c7.name }}</td>
															</tr>
														{% endfor %}
														</table></td>
														{% include "kitchen/tree_items.html" with items=il6 %}
													</tr>
												{% endfor %}
												</table></td>
												{% include "kitchen/tree_items.html" with items=il5 %}
											</tr>
										{% endfor %}
										</table></td>
										{% include "kitchen/tree_items.html" with items=il4 %}
									</tr>
								{% endfor %}
								</table></td>
								{% include "kitchen/tree_items.html" with items=il3 %}
							</tr>
						{% endfor %}
						</table></td>
						{% include "kitchen/tree_items.html" with items=il2 %}
					</tr>
					{% endfor %}
				</table></td>
				{% include "kitchen/tree_items.html" with items=il1 %}
			</tr>
			{% endfor %}
		</table></td>
		{% include "kitchen/tree_items.html" with items=il0 %}
	</tr>
	{% endfor %}
</table>